import React, { useState, useMemo } from 'react';
import {
  View, Text, TouchableOpacity, ScrollView, Modal,
  Platform, StyleSheet, KeyboardAvoidingView,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { WebFooter } from '../../src/components/layout/WebFooter';
import { useTheme } from '../../src/hooks/useTheme';
import { useResponsive } from '../../src/hooks/useResponsive';
import { ARGENTINA_TRAILS, ArgentinaTrail } from '../../src/data/argentinaTrails';
import { usePlannerStore } from '../../src/store/plannerStore';
import { useLangStore, Lang } from '../../src/store/langStore';
import { downloadGpx } from '../../src/utils/gpx';

// ─── Types ──────────────────────────────────────────────────────────────────

// `label` and `category` carry both languages; `category` also acts as the
// grouping key, so we key on the Spanish string (stable) and display via `lang`.
type Bi = { es: string; en: string };

interface CheckItem {
  id: string;
  label: Bi;
  checked: boolean;
  category: Bi;
  auto?: boolean; // auto-generated by rules
}

// ─── Checklist rule engine ───────────────────────────────────────────────────

const CAT = {
  hidratacion: { es: 'Hidratación', en: 'Hydration' },
  alimentacion: { es: 'Alimentación', en: 'Food' },
  navegacion: { es: 'Navegación', en: 'Navigation' },
  seguridad: { es: 'Seguridad', en: 'Safety' },
  ropa: { es: 'Ropa', en: 'Clothing' },
  salud: { es: 'Salud', en: 'Health' },
  comunicacion: { es: 'Comunicación', en: 'Communication' },
  documentos: { es: 'Documentos', en: 'Documents' },
  altaMontana: { es: 'Alta montaña', en: 'High mountain' },
  campamento: { es: 'Campamento', en: 'Camping' },
  tecnico: { es: 'Técnico', en: 'Technical' },
} as const;

const BASE_ITEMS: Omit<CheckItem, 'checked'>[] = [
  { id: 'agua', label: { es: 'Agua (mínimo 2 L)', en: 'Water (2 L minimum)' }, category: CAT.hidratacion },
  { id: 'comida', label: { es: 'Snacks y comida de marcha', en: 'Snacks and trail food' }, category: CAT.alimentacion },
  { id: 'mapa', label: { es: 'Mapa descargado offline', en: 'Map downloaded offline' }, category: CAT.navegacion },
  { id: 'brujula', label: { es: 'Brújula / GPS', en: 'Compass / GPS' }, category: CAT.navegacion },
  { id: 'botiquin', label: { es: 'Botiquín básico', en: 'Basic first-aid kit' }, category: CAT.seguridad },
  { id: 'silbato', label: { es: 'Silbato de emergencia', en: 'Emergency whistle' }, category: CAT.seguridad },
  { id: 'linterna', label: { es: 'Linterna con pilas extra', en: 'Flashlight with spare batteries' }, category: CAT.seguridad },
  { id: 'ropa_extra', label: { es: 'Capa extra de abrigo', en: 'Extra insulating layer' }, category: CAT.ropa },
  { id: 'chubasquero', label: { es: 'Capa impermeable', en: 'Waterproof layer' }, category: CAT.ropa },
  { id: 'calzado', label: { es: 'Botas de senderismo', en: 'Hiking boots' }, category: CAT.ropa },
  { id: 'protector', label: { es: 'Protector solar y labial', en: 'Sunscreen and lip balm' }, category: CAT.salud },
  { id: 'gafas', label: { es: 'Gafas de sol', en: 'Sunglasses' }, category: CAT.salud },
  { id: 'tel', label: { es: 'Teléfono cargado (vuelo offline)', en: 'Charged phone (airplane mode)' }, category: CAT.comunicacion },
  { id: 'efectivo', label: { es: 'Efectivo y DNI', en: 'Cash and ID' }, category: CAT.documentos },
];

function generateChecklist(trail: ArgentinaTrail): CheckItem[] {
  const extra: Omit<CheckItem, 'checked'>[] = [];

  if (trail.max_altitude_m >= 3000) {
    extra.push({ id: 'alt_ibuprofeno', label: { es: 'Ibuprofeno para mal de altura', en: 'Ibuprofen for altitude sickness' }, category: CAT.altaMontana, auto: true });
    extra.push({ id: 'alt_acetazolamida', label: { es: 'Acetazolamida (consultar médico)', en: 'Acetazolamide (consult a doctor)' }, category: CAT.altaMontana, auto: true });
    extra.push({ id: 'alt_baston', label: { es: 'Bastones de trekking', en: 'Trekking poles' }, category: CAT.altaMontana, auto: true });
  }
  if (trail.max_altitude_m >= 5000) {
    extra.push({ id: 'alt_oxigeno', label: { es: 'Suplemento de oxígeno portátil', en: 'Portable oxygen supplement' }, category: CAT.altaMontana, auto: true });
    extra.push({ id: 'alt_crampones', label: { es: 'Crampones / piolet', en: 'Crampons / ice axe' }, category: CAT.altaMontana, auto: true });
    extra.push({ id: 'alt_gafas_glaciar', label: { es: 'Gafas de glaciar CE 4', en: 'Glacier glasses (CE cat. 4)' }, category: CAT.altaMontana, auto: true });
  }
  if (trail.duration.unit === 'dias') {
    extra.push({ id: 'carpa', label: { es: 'Carpa / refugio', en: 'Tent / shelter' }, category: CAT.campamento, auto: true });
    extra.push({ id: 'saco', label: { es: 'Saco de dormir adecuado', en: 'Suitable sleeping bag' }, category: CAT.campamento, auto: true });
    extra.push({ id: 'colchoneta', label: { es: 'Esterilla aislante', en: 'Insulating sleeping pad' }, category: CAT.campamento, auto: true });
    extra.push({ id: 'hornillo', label: { es: 'Hornillo + combustible', en: 'Stove + fuel' }, category: CAT.campamento, auto: true });
    extra.push({ id: 'comida_dias', label: { es: `Comida para ${trail.duration.min}–${trail.duration.max} días`, en: `Food for ${trail.duration.min}–${trail.duration.max} days` }, category: CAT.alimentacion, auto: true });
  }
  if (trail.activity === 'alta_montana' || trail.activity === 'escalada') {
    extra.push({ id: 'casco', label: { es: 'Casco de escalada', en: 'Climbing helmet' }, category: CAT.tecnico, auto: true });
    extra.push({ id: 'arnes', label: { es: 'Arnés y cuerda', en: 'Harness and rope' }, category: CAT.tecnico, auto: true });
  }
  if (trail.permits_required) {
    extra.push({ id: 'permiso', label: { es: 'Permiso APN / parque (tramitar con antelación)', en: 'APN / park permit (arrange in advance)' }, category: CAT.documentos, auto: true });
  }
  if (trail.region === 'patagonia-sur' || trail.region === 'patagonia-norte') {
    extra.push({ id: 'viento', label: { es: 'Cortaviento extremo (Patagonia)', en: 'Extreme windbreaker (Patagonia)' }, category: CAT.ropa, auto: true });
  }

  const all = [...BASE_ITEMS, ...extra];
  return all.map((i) => ({ ...i, checked: false }));
}

// ─── Stage breakdown ─────────────────────────────────────────────────────────

function getStages(trail: ArgentinaTrail): { label: Bi; km: number; gain: number }[] {
  if (trail.duration.unit === 'horas') {
    return [
      { label: { es: 'Ida', en: 'Outbound' }, km: +(trail.distance_km / 2).toFixed(1), gain: Math.round(trail.elevation_gain_m * 0.6) },
      { label: { es: 'Vuelta', en: 'Return' }, km: +(trail.distance_km / 2).toFixed(1), gain: Math.round(trail.elevation_gain_m * 0.4) },
    ];
  }
  const days = trail.duration.min;
  const perDay = +(trail.distance_km / days).toFixed(1);
  return Array.from({ length: Math.min(days, 5) }, (_, i) => ({
    label: { es: `Día ${i + 1}`, en: `Day ${i + 1}` },
    km: perDay,
    gain: Math.round(trail.elevation_gain_m / days),
  }));
}

/** Translate a trail's duration unit for display. */
function unitLabel(unit: string, lang: Lang): string {
  if (unit === 'horas') return lang === 'es' ? 'horas' : 'hours';
  if (unit === 'dias') return lang === 'es' ? 'días' : 'days';
  return unit;
}

// ─── Difficulty color ─────────────────────────────────────────────────────────

const DIFF_COLOR: Record<string, string> = {
  facil: '#22c55e',
  moderado: '#f59e0b',
  dificil: '#ef4444',
  extremo: '#a855f7',
};
const DIFF_LABEL: Record<string, Bi> = {
  facil: { es: 'Fácil', en: 'Easy' },
  moderado: { es: 'Moderado', en: 'Moderate' },
  dificil: { es: 'Difícil', en: 'Hard' },
  extremo: { es: 'Extremo', en: 'Extreme' },
};

// ─── Route Picker Modal ───────────────────────────────────────────────────────

function RoutePicker({
  visible,
  onClose,
  onSelect,
  c,
}: {
  visible: boolean;
  onClose: () => void;
  onSelect: (t: ArgentinaTrail) => void;
  c: ThemeColors;
}) {
  const { t, lang } = useLangStore();
  const [search, setSearch] = React.useState('');
  const filtered = useMemo(
    () => ARGENTINA_TRAILS.filter(
      (t) =>
        t.name.toLowerCase().includes(search.toLowerCase()) ||
        t.province.toLowerCase().includes(search.toLowerCase())
    ),
    [search]
  );

  return (
    <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}>
      <TouchableOpacity style={pickerStyles.backdrop} activeOpacity={1} onPress={onClose}>
        <TouchableOpacity activeOpacity={1} style={[pickerStyles.sheet, { backgroundColor: c.surface, borderColor: c.border }]}>
          <View style={[pickerStyles.handle, { backgroundColor: c.border }]} />
          <Text style={[pickerStyles.title, { color: c.text }]}>{t('Elegir ruta', 'Choose a trail')}</Text>

          {/* Search */}
          <View style={[pickerStyles.searchWrap, { backgroundColor: c.elevated, borderColor: c.border }]}>
            <Ionicons name="search-outline" size={16} color={c.muted} />
            {Platform.OS === 'web' ? (
              // @ts-ignore
              <input
                value={search}
                onChange={(e: any) => setSearch(e.target.value)}
                placeholder={t('Buscar ruta o provincia…', 'Search trail or province…')}
                style={{
                  flex: 1, background: 'transparent', border: 'none', outline: 'none',
                  color: c.text, fontSize: 14, fontFamily: 'inherit',
                }}
              />
            ) : (
              <Text style={{ color: c.muted, flex: 1 }}>{t('Buscar…', 'Search…')}</Text>
            )}
          </View>

          <ScrollView showsVerticalScrollIndicator={false} style={{ maxHeight: 460 }}>
            {filtered.map((trail) => (
              <TouchableOpacity
                key={trail.id}
                style={[pickerStyles.item, { borderBottomColor: c.border }]}
                onPress={() => { onSelect(trail); onClose(); }}
                activeOpacity={0.7}
              >
                <View style={[pickerStyles.diffDot, { backgroundColor: DIFF_COLOR[trail.difficulty] }]} />
                <View style={{ flex: 1 }}>
                  <Text style={[pickerStyles.itemName, { color: c.text }]}>{trail.name}</Text>
                  <Text style={[pickerStyles.itemSub, { color: c.muted }]}>
                    {trail.province} · {trail.distance_km} km · {DIFF_LABEL[trail.difficulty][lang]}
                  </Text>
                </View>
                <Ionicons name="chevron-forward" size={16} color={c.muted} />
              </TouchableOpacity>
            ))}
          </ScrollView>
        </TouchableOpacity>
      </TouchableOpacity>
    </Modal>
  );
}

const pickerStyles = StyleSheet.create({
  backdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
  sheet: { borderTopLeftRadius: 28, borderTopRightRadius: 28, borderWidth: 1, padding: 20, paddingBottom: 36 },
  handle: { width: 40, height: 4, borderRadius: 2, alignSelf: 'center', marginBottom: 16 },
  title: { fontSize: 18, fontWeight: '800', letterSpacing: -0.4, marginBottom: 14 },
  searchWrap: {
    flexDirection: 'row', alignItems: 'center', gap: 8,
    borderRadius: 12, borderWidth: 1, paddingHorizontal: 12, paddingVertical: 10, marginBottom: 12,
  },
  item: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 14, borderBottomWidth: 1 },
  diffDot: { width: 10, height: 10, borderRadius: 5, flexShrink: 0 },
  itemName: { fontSize: 14, fontWeight: '700', marginBottom: 2 },
  itemSub: { fontSize: 12 },
});

// ─── Types ───────────────────────────────────────────────────────────────────

type ThemeColors = { bg: string; surface: string; elevated: string; border: string; text: string; muted: string };

// ─── Main screen ─────────────────────────────────────────────────────────────

export default function PlanificarScreen() {
  const { isDark } = useTheme();
  const { isWide } = useResponsive();
  const { t, lang } = useLangStore();

  const c: ThemeColors = isDark
    ? { bg: '#070b14', surface: '#0f1724', elevated: '#162035', border: '#1e2d42', text: '#f0f9ff', muted: '#64748b' }
    : { bg: '#f8fafc', surface: '#ffffff', elevated: '#f1f5f9', border: '#e2e8f0', text: '#0f172a', muted: '#64748b' };

  const { selectedTrailId, setSelectedTrail: persistTrail, checkedItems, toggleCheckedItem } = usePlannerStore();
  const [pickerOpen, setPickerOpen] = useState(false);
  const [activeTab, setActiveTab] = useState<'info' | 'etapas' | 'checklist'>('info');
  const [gpxDone, setGpxDone] = useState(false);

  const selectedTrail = useMemo(
    () => ARGENTINA_TRAILS.find((t) => t.id === selectedTrailId) ?? null,
    [selectedTrailId],
  );

  const checked = selectedTrail ? (checkedItems[selectedTrail.id] ?? []) : [];
  const checklist: CheckItem[] = useMemo(
    () =>
      selectedTrail
        ? generateChecklist(selectedTrail).map((i) => ({ ...i, checked: checked.includes(i.id) }))
        : [],
    [selectedTrail, checked.join(',')],
  );

  function selectTrail(trail: ArgentinaTrail) {
    persistTrail(trail.id);
    setActiveTab('info');
    setGpxDone(false);
  }

  function toggleItem(id: string) {
    if (selectedTrail) toggleCheckedItem(selectedTrail.id, id);
  }

  function exportGpx() {
    if (!selectedTrail) return;
    const ok = downloadGpx(
      selectedTrail.name,
      [{ lat: selectedTrail.coordinates.lat, lon: selectedTrail.coordinates.lon, name: selectedTrail.trailhead, ele: selectedTrail.max_altitude_m }],
      selectedTrail.description,
    );
    if (ok) {
      setGpxDone(true);
      setTimeout(() => setGpxDone(false), 2500);
    }
  }

  const checkedCount = checklist.filter((i) => i.checked).length;
  const stages = selectedTrail ? getStages(selectedTrail) : [];

  // Group checklist by category. Key on the Spanish string (stable) but keep
  // the bilingual label so the header can render in the active language.
  const categories = useMemo(() => {
    const map: Record<string, { label: Bi; items: CheckItem[] }> = {};
    checklist.forEach((item) => {
      const key = item.category.es;
      if (!map[key]) map[key] = { label: item.category, items: [] };
      map[key].items.push(item);
    });
    return Object.values(map);
  }, [checklist]);

  const content = (
    <ScrollView
      style={{ flex: 1 }}
      showsVerticalScrollIndicator={false}
      contentContainerStyle={{ paddingBottom: 0 }}
    >
      <View style={[s.pageInner, isWide && s.pageInnerWide]}>
      {/* Page header */}
      <View style={[s.pageHeader, { borderBottomColor: c.border }]}>
        <View style={s.pageHeaderLeft}>
          <Ionicons name="map" size={20} color="#22c55e" />
          <Text style={[s.pageHeaderTitle, { color: c.text }]}>{t('Planificar', 'Plan')}</Text>
        </View>
        <Text style={[s.pageHeaderSub, { color: c.muted }]}>{t('Diseñá tu caminata', 'Design your hike')}</Text>
      </View>
      {/* Hero / route picker ───────────────────────── */}
      <View style={[s.heroCard, { backgroundColor: c.surface, borderColor: c.border }]}>
        <View style={s.heroTop}>
          <View style={s.heroIcon}>
            <Ionicons name="map-outline" size={22} color="#22c55e" />
          </View>
          <View style={{ flex: 1 }}>
            <Text style={[s.heroTitle, { color: c.text }]}>
              {selectedTrail ? selectedTrail.name : t('Planificá tu ruta', 'Plan your route')}
            </Text>
            <Text style={[s.heroSub, { color: c.muted }]}>
              {selectedTrail
                ? `${selectedTrail.province} · ${selectedTrail.distance_km} km`
                : t('Seleccioná una ruta del catálogo', 'Pick a trail from the catalogue')}
            </Text>
          </View>
          <TouchableOpacity
            style={[s.pickBtn, { backgroundColor: selectedTrail ? c.elevated : '#16a34a', borderColor: selectedTrail ? c.border : '#16a34a' }]}
            onPress={() => setPickerOpen(true)}
            activeOpacity={0.8}
          >
            <Ionicons name={selectedTrail ? 'swap-horizontal' : 'add'} size={16} color={selectedTrail ? c.text : '#fff'} />
            <Text style={[s.pickBtnTxt, { color: selectedTrail ? c.text : '#fff' }]}>
              {selectedTrail ? t('Cambiar', 'Change') : t('Elegir ruta', 'Choose trail')}
            </Text>
          </TouchableOpacity>
        </View>

        {selectedTrail && (
          <View style={[s.diffRow, { borderTopColor: c.border }]}>
            <View style={[s.diffBadge, { backgroundColor: DIFF_COLOR[selectedTrail.difficulty] + '22' }]}>
              <View style={[s.diffDot, { backgroundColor: DIFF_COLOR[selectedTrail.difficulty] }]} />
              <Text style={[s.diffTxt, { color: DIFF_COLOR[selectedTrail.difficulty] }]}>
                {DIFF_LABEL[selectedTrail.difficulty][lang]}
              </Text>
            </View>
            <Text style={[s.metaTxt, { color: c.muted }]}>{selectedTrail.best_season}</Text>
            {selectedTrail.permits_required && (
              <View style={s.permitBadge}>
                <Ionicons name="document-text-outline" size={12} color="#f59e0b" />
                <Text style={s.permitTxt}>{t('Permiso requerido', 'Permit required')}</Text>
              </View>
            )}
          </View>
        )}
      </View>

      {!selectedTrail && (
        <View style={[s.emptyCard, { backgroundColor: c.surface, borderColor: c.border }]}>
          <Ionicons name="trail-sign-outline" size={40} color={c.border} />
          <Text style={[s.emptyTitle, { color: c.text }]}>{t('Empezá a planificar', 'Start planning')}</Text>
          <Text style={[s.emptyText, { color: c.muted }]}>
            {t(
              'Elegí una ruta del catálogo para ver etapas, estadísticas y generar automáticamente tu lista de equipamiento.',
              'Pick a trail from the catalogue to see stages, stats and automatically generate your gear checklist.',
            )}
          </Text>
          <TouchableOpacity style={s.emptyBtn} onPress={() => setPickerOpen(true)} activeOpacity={0.8}>
            <Text style={s.emptyBtnTxt}>{t('Ver catálogo de rutas', 'Browse trail catalogue')}</Text>
          </TouchableOpacity>
        </View>
      )}

      {selectedTrail && (
        <>
          {/* Stats strip */}
          <View style={[s.statsStrip, { backgroundColor: c.surface, borderColor: c.border }]}>
            {[
              { icon: 'resize-outline' as const, label: t('Distancia', 'Distance'), value: `${selectedTrail.distance_km} km` },
              { icon: 'trending-up-outline' as const, label: t('Desnivel', 'Elevation'), value: `+${selectedTrail.elevation_gain_m} m` },
              { icon: 'arrow-up-outline' as const, label: t('Altitud máx.', 'Max. altitude'), value: `${selectedTrail.max_altitude_m} m` },
              {
                icon: 'time-outline' as const,
                label: t('Duración', 'Duration'),
                value: `${selectedTrail.duration.min}–${selectedTrail.duration.max} ${unitLabel(selectedTrail.duration.unit, lang)}`,
              },
            ].map((stat) => (
              <View key={stat.label} style={s.statItem}>
                <Ionicons name={stat.icon} size={16} color="#22c55e" />
                <Text style={[s.statValue, { color: c.text }]}>{stat.value}</Text>
                <Text style={[s.statLabel, { color: c.muted }]}>{stat.label}</Text>
              </View>
            ))}
          </View>

          {/* Tab nav */}
          <View style={[s.tabRow, { backgroundColor: c.surface, borderColor: c.border }]}>
            {(['info', 'etapas', 'checklist'] as const).map((tab) => {
              const labels = { info: t('Información', 'Info'), etapas: t('Etapas', 'Stages'), checklist: `${t('Equipo', 'Gear')} (${checkedCount}/${checklist.length})` };
              const active = activeTab === tab;
              return (
                <TouchableOpacity
                  key={tab}
                  style={[s.tabPill, active && { backgroundColor: c.elevated }]}
                  onPress={() => setActiveTab(tab)}
                  activeOpacity={0.7}
                >
                  <Text
                    numberOfLines={1}
                    style={[s.tabLabel, { color: active ? c.text : c.muted, fontWeight: active ? '700' : '500' }]}
                  >
                    {labels[tab]}
                  </Text>
                </TouchableOpacity>
              );
            })}
          </View>

          {/* Tab content */}
          {activeTab === 'info' && (
            <View style={[s.card, { backgroundColor: c.surface, borderColor: c.border }]}>
              <Text style={[s.cardTitle, { color: c.text }]}>{t('Descripción', 'Description')}</Text>
              <Text style={[s.cardBody, { color: c.muted }]}>{selectedTrail.description}</Text>
              <View style={[s.infoRow, { borderTopColor: c.border }]}>
                <Ionicons name="location-outline" size={14} color="#22c55e" />
                <Text style={[s.infoRowTxt, { color: c.muted }]}>{t('Punto de partida:', 'Trailhead:')} {selectedTrail.trailhead}</Text>
              </View>
              <View style={[s.infoRow, { borderTopColor: c.border }]}>
                <Ionicons name="calendar-outline" size={14} color="#22c55e" />
                <Text style={[s.infoRowTxt, { color: c.muted }]}>{t('Mejor temporada:', 'Best season:')} {selectedTrail.best_season}</Text>
              </View>
              <View style={[s.infoRow, { borderTopColor: c.border }]}>
                <Ionicons name="pricetag-outline" size={14} color="#22c55e" />
                <Text style={[s.infoRowTxt, { color: c.muted }]}>{selectedTrail.tags.join(' · ')}</Text>
              </View>
              <View style={{ flexDirection: 'row', gap: 8, flexWrap: 'wrap' }}>
                <TouchableOpacity style={s.aiBtn} onPress={exportGpx} activeOpacity={0.8}>
                  <Ionicons name={gpxDone ? 'checkmark-circle-outline' : 'download-outline'} size={16} color="#22c55e" />
                  <Text style={s.aiBtnTxt}>{gpxDone ? t('GPX descargado', 'GPX downloaded') : t('Exportar GPX', 'Export GPX')}</Text>
                </TouchableOpacity>
              </View>
            </View>
          )}

          {activeTab === 'etapas' && (
            <View style={[s.card, { backgroundColor: c.surface, borderColor: c.border }]}>
              <Text style={[s.cardTitle, { color: c.text }]}>{t('Etapas sugeridas', 'Suggested stages')}</Text>
              {stages.map((stage, i) => (
                <View key={i} style={[s.stageRow, { borderBottomColor: c.border }]}>
                  <View style={s.stageNum}>
                    <Text style={s.stageNumTxt}>{i + 1}</Text>
                  </View>
                  <View style={{ flex: 1 }}>
                    <Text style={[s.stageName, { color: c.text }]}>{stage.label[lang]}</Text>
                    <Text style={[s.stageSub, { color: c.muted }]}>{stage.km} km · +{stage.gain} m {t('desnivel', 'gain')}</Text>
                  </View>
                </View>
              ))}
              <View style={[s.stageNote, { backgroundColor: isDark ? 'rgba(56,189,248,0.07)' : 'rgba(14,165,233,0.06)', borderColor: isDark ? 'rgba(56,189,248,0.2)' : 'rgba(14,165,233,0.2)' }]}>
                <Ionicons name="information-circle-outline" size={14} color="#38bdf8" />
                <Text style={[s.stageNoteTxt, { color: '#38bdf8' }]}>
                  {t(
                    'Las etapas son estimaciones basadas en distancia y desnivel. Consultá con guías locales o la APN.',
                    'Stages are estimates based on distance and elevation gain. Check with local guides or the APN.',
                  )}
                </Text>
              </View>
            </View>
          )}

          {activeTab === 'checklist' && (
            <View style={[s.card, { backgroundColor: c.surface, borderColor: c.border }]}>
              <View style={s.checklistHeader}>
                <Text style={[s.cardTitle, { color: c.text }]}>{t('Lista de equipamiento', 'Gear checklist')}</Text>
                <View style={[s.progressBadge, { backgroundColor: c.elevated }]}>
                  <Text style={[s.progressTxt, { color: '#22c55e' }]}>{checkedCount}/{checklist.length}</Text>
                </View>
              </View>
              {checklist.some((i) => i.auto) && (
                <View style={[s.autoBanner, { backgroundColor: isDark ? 'rgba(34,197,94,0.08)' : 'rgba(34,197,94,0.06)', borderColor: 'rgba(34,197,94,0.25)' }]}>
                  <Ionicons name="flash-outline" size={14} color="#22c55e" />
                  <Text style={[s.autoBannerTxt, { color: '#22c55e' }]}>
                    {t(
                      'Los ítems con estrella fueron generados automáticamente para esta ruta',
                      'Starred items were generated automatically for this trail',
                    )}
                  </Text>
                </View>
              )}
              {categories.map(({ label, items }) => (
                <View key={label.es} style={s.checkCat}>
                  <Text style={[s.checkCatTitle, { color: c.muted }]}>{label[lang].toUpperCase()}</Text>
                  {items.map((item) => (
                    <TouchableOpacity
                      key={item.id}
                      style={[s.checkRow, { borderBottomColor: c.border }]}
                      onPress={() => toggleItem(item.id)}
                      activeOpacity={0.7}
                    >
                      <View style={[
                        s.checkbox,
                        { borderColor: item.checked ? '#22c55e' : c.border },
                        item.checked && { backgroundColor: '#22c55e' },
                      ]}>
                        {item.checked && <Ionicons name="checkmark" size={12} color="#fff" />}
                      </View>
                      <Text style={[s.checkLabel, { color: item.checked ? c.muted : c.text, textDecorationLine: item.checked ? 'line-through' : 'none' }]}>
                        {item.label[lang]}
                      </Text>
                      {item.auto && <Ionicons name="star" size={10} color="#22c55e" style={{ opacity: 0.7 }} />}
                    </TouchableOpacity>
                  ))}
                </View>
              ))}
            </View>
          )}
        </>
      )}
      <View style={{ height: 64 }} />
      </View>
      {Platform.OS === 'web' && <WebFooter />}
    </ScrollView>
  );

  const isWeb = Platform.OS === 'web';

  return (
    <KeyboardAvoidingView style={[s.root, { backgroundColor: c.bg }]} behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
      {content}

      <RoutePicker
        visible={pickerOpen}
        onClose={() => setPickerOpen(false)}
        onSelect={selectTrail}
        c={c}
      />
    </KeyboardAvoidingView>
  );
}

const s = StyleSheet.create({
  root: { flex: 1 },
  pageInner: { maxWidth: 800, alignSelf: 'center', width: '100%' },
  pageInnerWide: {},
  pageHeader: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 20, paddingVertical: 16, borderBottomWidth: 1,
  },
  pageHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  pageHeaderTitle: { fontSize: 20, fontWeight: '800', letterSpacing: -0.4 },
  pageHeaderSub: { fontSize: 13 },

  // Hero card
  heroCard: {
    margin: 16, borderRadius: 20, borderWidth: 1, padding: 16,
  },
  heroTop: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  heroIcon: {
    width: 44, height: 44, borderRadius: 12,
    backgroundColor: 'rgba(34,197,94,0.12)', borderWidth: 1, borderColor: 'rgba(34,197,94,0.25)',
    alignItems: 'center', justifyContent: 'center',
  },
  heroTitle: { fontSize: 16, fontWeight: '800', letterSpacing: -0.3, marginBottom: 2 },
  heroSub: { fontSize: 12 },
  pickBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 6,
    paddingHorizontal: 14, paddingVertical: 8, borderRadius: 999, borderWidth: 1,
  },
  pickBtnTxt: { fontSize: 13, fontWeight: '700' },
  diffRow: {
    flexDirection: 'row', alignItems: 'center', gap: 10,
    marginTop: 14, paddingTop: 14, borderTopWidth: 1, flexWrap: 'wrap',
  },
  diffBadge: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 999 },
  diffDot: { width: 8, height: 8, borderRadius: 4 },
  diffTxt: { fontSize: 12, fontWeight: '700' },
  metaTxt: { fontSize: 12 },
  permitBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: 'rgba(245,158,11,0.12)', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 999 },
  permitTxt: { fontSize: 11, fontWeight: '600', color: '#f59e0b' },

  // Empty
  emptyCard: {
    margin: 16, borderRadius: 20, borderWidth: 1, padding: 32,
    alignItems: 'center', gap: 12,
  },
  emptyTitle: { fontSize: 18, fontWeight: '800', letterSpacing: -0.4 },
  emptyText: { fontSize: 14, textAlign: 'center', lineHeight: 22 },
  emptyBtn: { backgroundColor: '#16a34a', paddingHorizontal: 24, paddingVertical: 12, borderRadius: 999, marginTop: 4 },
  emptyBtnTxt: { color: '#fff', fontSize: 14, fontWeight: '700' },

  // Stats
  statsStrip: {
    flexDirection: 'row', marginHorizontal: 16, marginBottom: 12,
    borderRadius: 16, borderWidth: 1, padding: 16, gap: 4,
  },
  statItem: { flex: 1, alignItems: 'center', gap: 4 },
  statValue: { fontSize: 13, fontWeight: '800', letterSpacing: -0.3 },
  statLabel: { fontSize: 10, fontWeight: '600' },

  // Tabs
  tabRow: {
    flexDirection: 'row', marginHorizontal: 16, marginBottom: 12,
    borderRadius: 16, borderWidth: 1, padding: 4, gap: 4,
  },
  tabPill: {
    flex: 1, paddingVertical: 9, paddingHorizontal: 4,
    borderRadius: 12, alignItems: 'center',
  },
  tabLabel: { fontSize: 12 },

  // Cards
  card: {
    marginHorizontal: 16, marginBottom: 12, borderRadius: 20, borderWidth: 1, padding: 16, gap: 12,
  },
  cardTitle: { fontSize: 15, fontWeight: '800', letterSpacing: -0.3 },
  cardBody: { fontSize: 14, lineHeight: 22 },
  infoRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8, paddingTop: 10, borderTopWidth: 1 },
  infoRowTxt: { fontSize: 13, flex: 1, lineHeight: 20 },
  aiBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 8,
    backgroundColor: 'rgba(34,197,94,0.1)', borderRadius: 12,
    paddingHorizontal: 14, paddingVertical: 10, borderWidth: 1, borderColor: 'rgba(34,197,94,0.25)',
    alignSelf: 'flex-start',
  },
  aiBtnTxt: { fontSize: 13, fontWeight: '700', color: '#22c55e' },

  // Stages
  stageRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 12, borderBottomWidth: 1 },
  stageNum: { width: 28, height: 28, borderRadius: 14, backgroundColor: 'rgba(34,197,94,0.15)', alignItems: 'center', justifyContent: 'center' },
  stageNumTxt: { fontSize: 13, fontWeight: '800', color: '#22c55e' },
  stageName: { fontSize: 14, fontWeight: '700', marginBottom: 2 },
  stageSub: { fontSize: 12 },
  stageNote: { flexDirection: 'row', gap: 8, padding: 12, borderRadius: 12, borderWidth: 1, alignItems: 'flex-start' },
  stageNoteTxt: { fontSize: 12, lineHeight: 18, flex: 1 },

  // Checklist
  checklistHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  progressBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 999 },
  progressTxt: { fontSize: 12, fontWeight: '700' },
  autoBanner: {
    flexDirection: 'row', gap: 8, padding: 10, borderRadius: 12, borderWidth: 1, alignItems: 'center',
  },
  autoBannerTxt: { fontSize: 12, flex: 1, lineHeight: 18 },
  checkCat: { gap: 2, marginTop: 8 },
  checkCatTitle: { fontSize: 9, fontWeight: '800', letterSpacing: 1.5, marginBottom: 8 },
  checkRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 10, borderBottomWidth: 1 },
  checkbox: { width: 20, height: 20, borderRadius: 6, borderWidth: 2, alignItems: 'center', justifyContent: 'center' },
  checkLabel: { fontSize: 13, flex: 1 },
});
